"""Auto-fix INC-77
Title: Repeated error code SERVICE_DOWN: 24 occurrences
Generated by LogSentinel AI
"""

diff --git a/billing_service.py b/billing_service.py
--- a/billing_service.py
+++ b/billing_service.py
@@ -10,7 +10,7 @@
 import psycopg2
 
-conn = psycopg2.connect(
+conn = psycopg2.connect(
     host="localhost",
     database="billing_db",
     user="billing_user",
-    password="billing_password",
+    password="billing_password",
     minconn=5,
-    maxconn=20
+    maxconn=50
 )
