"""Auto-fix INC-81
Title: Repeated error code POOL_LOW: 12 occurrences
Generated by LogSentinel AI
"""

diff --git a/billing_service.py b/billing_service.py
--- a/billing_service.py
+++ b/billing_service.py
@@ -10,7 +10,7 @@
 from sqlalchemy import create_engine
 
-engine = create_engine('postgresql://user:password@host:port/dbname', pool_size=20)
+engine = create_engine('postgresql://user:password@host:port/dbname', pool_size=50)
 
 # ...
