"""Auto-fix INC-13
Title: Repeated error code POOL_LOW: 17 occurrences
Generated by LogSentinel AI
"""

diff --git a/billing_service.py b/billing_service.py
--- a/billing_service.py
+++ b/billing_service.py
@@ -10,7 +10,7 @@
 import os
 import psycopg2
-from psycopg2 import pool
+from psycopg2 import pool, ThreadedConnectionPool
 
 # ... (rest of the code remains the same)
-
+connection_pool = ThreadedConnectionPool(
+    minconn=10, maxconn=50, 
+    host='localhost', database='billing_db', 
+    user='billing_user', password='billing_password'
+)

